GET http://localhost:5029/games

###
GET http://localhost:5029/genres    

####
GET http://localhost:5029/games/600f842e-16f4-456e-bd7b-8bf04f57dc9c

####
POST http://localhost:5029/games
Content-Type: application/json  

{
    "name": "PubG",
    "genreid": "76b7e1a2-fe0a-4200-baa5-7fa0608cbdab",
    "price": 59.99,
    "releasedate": "2021-12-08",
    "description": "Battle royale game"
}

####
PUT http://localhost:5029/games/388816e3-97fd-46fb-8900-5f1058cdb5f0
Content-Type: application/json  

{
    "name": "Sherlock Holmes",
    "genreid": "cc197a1c-b61a-40d7-af24-9c2b94b2b52e",
    "price":60.99,
    "releaseDate": "2021-12-08",
    "description": "Detective adventure game"
}

###
DELETE http://localhost:5029/games/388816e3-97fd-46fb-8900-5f1058cdb5f0