GET http://localhost:5029/games

###
GET http://localhost:5029/genres    

####
GET http://localhost:5029/games/E678CF9D-F51C-475D-B6C0-0D3FD827A111

####
POST http://localhost:5029/games
Content-Type: application/json  

{
    "name": "PubG",
    "genreid": "FF882709-9F0D-43C0-9AC3-604000CAE132",
    "price": 59.99,
    "releasedate": "2021-12-08",
    "description": "Battle royale game"
}

####
PUT http://localhost:5029/games/E678CF9D-F51C-475D-B6C0-0D3FD827A111
Content-Type: application/json  

{
    "name": "Sherlock Holmes 2",
    "genreid": "FF882709-9F0D-43C0-9AC3-604000CAE132",
    "price":60.99,
    "releaseDate": "2021-12-08",
    "description": "Detective adventure game"
}

###
DELETE http://localhost:5029/games/388816e3-97fd-46fb-8900-5f1058cdb5f0