GET http://localhost:5029/games

####
GET http://localhost:5029/games/dbccb60a-8d4d-493e-ad34-3a678bc65693

####
POST http://localhost:5029/games
Content-Type: application/json  

{
    "name": "PubG",
    "genreid": "3061b302-2608-4208-abf3-4caee415db3a",
    "price": 59.99,
    "releasedate": "2021-12-08",
    "description": "Battle royale game"
}

####
PUT http://localhost:5029/games/49438bfa-ef75-4ab5-9d00-46bfe1dd367b
Content-Type: application/json  

{
    "name": "Fortnite",
    "genre": "Shooter",
    "price": 50.99,
    "releaseDate": "2021-12-08"
}

###
DELETE http://localhost:5029/games/e8274569-9ebb-4cef-865b-5f3ff50ab5ce